\subsubsection* { Pythagorean Triples }
The Pythagorean triples are uniquely generated by
\[
	a = k \cdot(m ^ 2 - n ^ 2), \quad b = k \cdot(2mn), \quad c = k \cdot(m ^ 2 + n ^ 2),
	\]
	with $m > n > 0$, $k > 0$, $m \perp n$, and either $m$ or $n$ even.